#!/bin/bash
# ── App Setup ────────────────────────────────────────────────────────
# Downloads the OIG release tarball, configures .env, sets up swap,
# builds and starts the app.
#
# Two modes:
#   Docker   (HAS_DOCKER=1) — uses docker compose (bare metal, VPS)
#   Direct   (HAS_DOCKER=0) — installs services natively (RunPod, containers)
#
# Expects these variables from the parent install.sh:
#   INSTALL_MODE      — "local" or "production"
#   HAS_DOCKER        — "1" or "0"
#   HAS_SYSTEMD       — "1" or "0"
#   OIG_TARBALL_URL   — URL to the release tarball on GitHub Releases
#   OIG_VERSION       — version string (e.g. "0.1.0")
set -e

APP_DIR="/opt/oig"
INSTALL_MODE="${INSTALL_MODE:-local}"

echo "=== Setting Up Open Image Generator v${OIG_VERSION} ==="
echo "Mode: $INSTALL_MODE"
echo ""

# ── Download or update app ───────────────────────────────────────────
if [ -d "$APP_DIR" ] && [ -f "$APP_DIR/.oig-version" ]; then
    INSTALLED_VERSION=$(cat "$APP_DIR/.oig-version" | tr -d '[:space:]')
    if [ "$INSTALLED_VERSION" = "$OIG_VERSION" ]; then
        echo "v${OIG_VERSION} is already installed. Skipping download."
    else
        echo "Upgrading from v${INSTALLED_VERSION} to v${OIG_VERSION}..."
        echo "Downloading release tarball..."
        TMP_TAR=$(mktemp)
        wget --quiet --show-progress -O "$TMP_TAR" "$OIG_TARBALL_URL"
        # Preserve .env and postgres data across upgrades
        sudo rm -rf "$APP_DIR/api" "$APP_DIR/app" "$APP_DIR/Caddyfile"* "$APP_DIR/Dockerfile"* "$APP_DIR/docker-compose"*
        tar -xzf "$TMP_TAR" -C "$APP_DIR" --strip-components=1
        rm -f "$TMP_TAR"
        echo "$OIG_VERSION" > "$APP_DIR/.oig-version"
        echo "Upgrade extracted."
    fi
else
    echo "Downloading OIG v${OIG_VERSION}..."
    sudo mkdir -p "$APP_DIR"
    sudo chown "$USER:$USER" "$APP_DIR"
    TMP_TAR=$(mktemp)
    wget --quiet --show-progress -O "$TMP_TAR" "$OIG_TARBALL_URL"
    tar -xzf "$TMP_TAR" -C "$APP_DIR" --strip-components=1
    rm -f "$TMP_TAR"
    echo "$OIG_VERSION" > "$APP_DIR/.oig-version"
    echo "Download complete."
fi

cd "$APP_DIR"

# ── Swap space ────────────────────────────────────────────────────────
# Containers (RunPod, Docker) can't create swap — skip gracefully.
if [ -f /swapfile ]; then
    echo "Swap already exists."
elif [ -f /.dockerenv ] || grep -q 'docker\|lxc\|kubepods' /proc/1/cgroup 2>/dev/null; then
    echo "Container detected — skipping swap setup."
else
    echo ""
    echo "Adding 8GB swap space (ComfyUI's VAE decode can spill to system RAM)..."
    sudo fallocate -l 8G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    if ! grep -q '/swapfile' /etc/fstab; then
        echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
    fi
    echo "Swap configured."
fi

# ── Generate .env ─────────────────────────────────────────────────────
# Only generate .env on first install — upgrades keep existing config
if [ -f "$APP_DIR/.env" ]; then
    echo ""
    echo "Existing .env found — keeping current configuration."
    echo "(Edit $APP_DIR/.env manually if you need to change settings)"
else
    echo ""
    echo "=== Configuration ==="

    # Auto-generate secrets
    JWT_SECRET=$(openssl rand -hex 32)
    POSTGRES_PASSWORD=$(openssl rand -hex 32)

    # Service hostnames differ between Docker and direct install
    if [ "${HAS_DOCKER:-1}" = "1" ]; then
        COMFY_HOST="host.docker.internal"
        OLLAMA_HOST="host.docker.internal"
    else
        COMFY_HOST="localhost"
        OLLAMA_HOST="localhost"
    fi

    if [ "$INSTALL_MODE" = "local" ]; then
        # ── Local mode ────────────────────────────────────────────────
        echo ""
        echo "Local mode — the app will be available at http://localhost"
        echo "No domain, SSL, or email service required."
        echo ""

        echo "--- Admin Account ---"
        read -p "Admin email: " ADMIN_EMAIL
        read -p "Admin username [admin]: " ADMIN_USERNAME
        ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
        while true; do
            read -sp "Admin password (min 8 chars): " ADMIN_PASSWORD
            echo ""
            if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
                break
            fi
            echo "  Password must be at least 8 characters."
        done

        echo ""
        read -p "Site name [Open Image Generator]: " SITE_NAME
        SITE_NAME="${SITE_NAME:-Open Image Generator}"

        cat > "$APP_DIR/.env" <<EOF
# ── Generated by installer (local mode) ──────────────────────────────
# $(date)
# OIG v${OIG_VERSION}

# Database
POSTGRES_USER=oig
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=open_image_gen

# Backend
BACKEND_PORT=8000
WORKERS=2
JWT_SECRET=$JWT_SECRET
JWT_EXPIRE_MINUTES=480

# URLs
CORS_ORIGIN=http://localhost
APP_URL=http://localhost

# GPU Services
COMFYUI_URL=http://$COMFY_HOST:8188
LMSTUDIO_URL=http://$OLLAMA_HOST:11434
LLM_MODEL=qwen3:8b-nothink

# Admin
SUPERADMIN_EMAIL=$ADMIN_EMAIL
SUPERADMIN_PASSWORD=$ADMIN_PASSWORD
EOF

        COMPOSE_FILE="docker-compose.local.yml"

    else
        # ── Production mode ───────────────────────────────────────────
        echo ""
        echo "Production mode — requires a domain and Cloudflare DNS."
        echo ""

        read -p "Domain (e.g. mysite.com): " DOMAIN
        while [ -z "$DOMAIN" ]; do
            read -p "  Domain is required: " DOMAIN
        done

        read -p "Cloudflare API token: " CF_TOKEN
        while [ -z "$CF_TOKEN" ]; do
            read -p "  Cloudflare token is required for SSL: " CF_TOKEN
        done

        echo ""
        echo "--- Admin Account ---"
        read -p "Admin email: " ADMIN_EMAIL
        read -p "Admin username [admin]: " ADMIN_USERNAME
        ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
        while true; do
            read -sp "Admin password (min 8 chars): " ADMIN_PASSWORD
            echo ""
            if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
                break
            fi
            echo "  Password must be at least 8 characters."
        done

        echo ""
        echo "--- Email (optional — skip to configure later in admin UI) ---"
        read -p "Brevo API key [skip]: " BREVO_KEY
        read -p "From email address [skip]: " FROM_EMAIL
        read -p "From name [Open Image Generator]: " FROM_NAME
        FROM_NAME="${FROM_NAME:-Open Image Generator}"

        read -p "Site name [Open Image Generator]: " SITE_NAME
        SITE_NAME="${SITE_NAME:-Open Image Generator}"

        # Write Caddyfile with the domain
        if [ ! -f "$APP_DIR/Caddyfile" ]; then
            echo "ERROR: Caddyfile not found in $APP_DIR"
            exit 1
        fi
        sed "s/yourdomain.com/$DOMAIN/g" "$APP_DIR/Caddyfile" > "$APP_DIR/Caddyfile.tmp"
        mv "$APP_DIR/Caddyfile.tmp" "$APP_DIR/Caddyfile"

        cat > "$APP_DIR/.env" <<EOF
# ── Generated by installer (production mode) ─────────────────────────
# $(date)
# OIG v${OIG_VERSION}

# Database
POSTGRES_USER=oig
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=open_image_gen

# Backend
BACKEND_PORT=8000
WORKERS=2
JWT_SECRET=$JWT_SECRET
JWT_EXPIRE_MINUTES=480

# URLs
CORS_ORIGIN=https://$DOMAIN
APP_URL=https://$DOMAIN

# GPU Services
COMFYUI_URL=http://$COMFY_HOST:8188
LMSTUDIO_URL=http://$OLLAMA_HOST:11434
LLM_MODEL=qwen3:8b-nothink

# Cloudflare
CLOUDFLARE_API_TOKEN=$CF_TOKEN

# Admin
SUPERADMIN_EMAIL=$ADMIN_EMAIL
SUPERADMIN_PASSWORD=$ADMIN_PASSWORD

# Email (Brevo)
BREVO_API_KEY="${BREVO_KEY:-}"
EMAIL_FROM_NAME="$FROM_NAME"
EMAIL_FROM_EMAIL="${FROM_EMAIL:-}"
EOF

        COMPOSE_FILE="docker-compose.prod.yml"
    fi
fi

# ── Build and start ───────────────────────────────────────────────────

if [ "${HAS_DOCKER:-1}" = "1" ]; then
    # ═══════════════════════════════════════════════════════════════════
    # Docker path (bare metal, VPS, Linode, etc.)
    # ═══════════════════════════════════════════════════════════════════

    # Determine compose file if not set (upgrade path)
    if [ -z "$COMPOSE_FILE" ]; then
        if grep -q "CORS_ORIGIN=http://localhost" "$APP_DIR/.env" 2>/dev/null; then
            COMPOSE_FILE="docker-compose.local.yml"
        else
            COMPOSE_FILE="docker-compose.prod.yml"
        fi
    fi

    echo ""
    echo "=== Building and starting services (Docker) ==="
    echo "This will build the frontend and backend Docker images (may take a few minutes)..."
    echo ""

    # Use sudo if user isn't in docker group yet (root never needs sudo)
    if [ "$(id -u)" = "0" ] || groups "$USER" | grep -q docker; then
        docker compose -f "$COMPOSE_FILE" up -d --build
    else
        sudo docker compose -f "$COMPOSE_FILE" up -d --build
    fi

else
    # ═══════════════════════════════════════════════════════════════════
    # Direct-install path (RunPod, containers without Docker support)
    # ═══════════════════════════════════════════════════════════════════

    echo ""
    echo "=== Installing services directly (no Docker) ==="
    echo ""

    # Load .env variables (grep out comments, eval handles quoted values)
    set -a
    eval "$(grep -v '^\s*#' "$APP_DIR/.env" | grep -v '^\s*$')"
    set +a

    # ── PostgreSQL ────────────────────────────────────────────────────
    if ! command -v psql &>/dev/null; then
        echo "Installing PostgreSQL..."
        sudo apt-get update -qq
        sudo apt-get install -y -qq postgresql postgresql-contrib
    else
        echo "PostgreSQL already installed."
    fi

    # Start PostgreSQL
    if [ "$HAS_SYSTEMD" = "1" ]; then
        sudo systemctl start postgresql
        sudo systemctl enable postgresql
    else
        # Start directly (containers)
        if ! pgrep -x postgres &>/dev/null; then
            sudo pg_ctlcluster $(pg_lsclusters -h | head -1 | awk '{print $1, $2}') start 2>/dev/null || \
            sudo -u postgres pg_ctl start -D /var/lib/postgresql/*/main -l /var/log/postgresql/postgresql.log 2>/dev/null || \
            sudo service postgresql start 2>/dev/null || true
        fi
    fi

    # Wait for PostgreSQL to be ready
    echo "Waiting for PostgreSQL..."
    for _ in {1..30}; do
        if sudo -u postgres psql -c "SELECT 1" &>/dev/null; then
            break
        fi
        sleep 1
    done

    # Create database and user (idempotent)
    echo "Configuring database..."
    sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${POSTGRES_USER}'" | grep -q 1 || \
        sudo -u postgres psql -c "CREATE USER ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';"
    sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${POSTGRES_DB}'" | grep -q 1 || \
        sudo -u postgres psql -c "CREATE DATABASE ${POSTGRES_DB} OWNER ${POSTGRES_USER};"
    # Ensure password is up to date
    sudo -u postgres psql -c "ALTER USER ${POSTGRES_USER} WITH PASSWORD '${POSTGRES_PASSWORD}';" 2>/dev/null || true

    echo "PostgreSQL ready."

    # ── Redis ─────────────────────────────────────────────────────────
    if ! command -v redis-server &>/dev/null; then
        echo "Installing Redis..."
        sudo apt-get install -y -qq redis-server
    else
        echo "Redis already installed."
    fi

    if [ "$HAS_SYSTEMD" = "1" ]; then
        sudo systemctl start redis-server
        sudo systemctl enable redis-server
    else
        # Stop any daemonized Redis so supervisord can manage it
        redis-cli shutdown 2>/dev/null || true
        sleep 1

        # Add supervisord config for Redis
        mkdir -p /etc/supervisor/conf.d
        cat > /etc/supervisor/conf.d/redis.conf <<REOF
[program:redis]
command=redis-server --daemonize no
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/redis.log
stderr_logfile=/var/log/redis.log
REOF
    fi

    echo "Redis ready."

    # ── Node.js + Build Frontend ──────────────────────────────────────
    if ! command -v node &>/dev/null; then
        echo "Installing Node.js 20..."
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y -qq nodejs
    else
        echo "Node.js already installed: $(node --version)"
    fi

    echo "Building frontend..."
    cd "$APP_DIR/app"
    npm ci --quiet
    npm run build
    FRONTEND_DIR="$APP_DIR/app/dist"
    echo "Frontend built."

    # ── Caddy ─────────────────────────────────────────────────────────
    # In direct-install mode, Caddy always serves plain HTTP on port 80.
    # For production, Cloudflare Tunnel handles external TLS (set up below).
    if ! command -v caddy &>/dev/null; then
        echo "Installing Caddy..."
        sudo apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg 2>/dev/null
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
        sudo apt-get update -qq
        sudo apt-get install -y -qq caddy
    else
        echo "Caddy already installed."
    fi

    # Write Caddyfile — always plain HTTP (Cloudflare Tunnel or direct access)
    mkdir -p /etc/caddy
    cat > /etc/caddy/Caddyfile <<CEOF
:80 {
	handle /api/* {
		uri strip_prefix /api
		reverse_proxy localhost:${BACKEND_PORT:-8000}
	}

	handle {
		root * $FRONTEND_DIR
		try_files {path} /index.html
		file_server
	}

	header {
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
		Referrer-Policy strict-origin-when-cross-origin
	}
}
CEOF

    # Start/restart Caddy
    if [ "$HAS_SYSTEMD" = "1" ]; then
        sudo systemctl restart caddy
        sudo systemctl enable caddy
    else
        # Kill existing Caddy if running
        pkill caddy 2>/dev/null || true
        sleep 1
        mkdir -p /etc/supervisor/conf.d
        cat > /etc/supervisor/conf.d/caddy.conf <<CEOF
[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/caddy.log
stderr_logfile=/var/log/caddy.log
CEOF
    fi

    echo "Caddy configured."

    # ── Backend (Python) ──────────────────────────────────────────────
    echo "Setting up backend..."
    cd "$APP_DIR/api"

    if [ ! -d "venv" ]; then
        python3 -m venv venv
    fi

    source venv/bin/activate
    pip install --quiet -r requirements.txt

    # Set DATABASE_URL for direct Postgres (localhost, not Docker service name)
    export DATABASE_URL="postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}"
    export REDIS_URL="redis://localhost:6379/0"

    # Run migrations
    echo "Running database migrations..."
    alembic upgrade head

    deactivate

    # Create backend startup script
    cat > "$APP_DIR/api/start.sh" <<BEOF
#!/bin/bash
cd $APP_DIR/api
source venv/bin/activate

# Load .env (eval handles quoted values safely)
set -a
eval "\$(grep -v '^\s*#' $APP_DIR/.env | grep -v '^\s*\$')"
set +a

# Override Docker-style URLs for direct install
export DATABASE_URL="postgresql+asyncpg://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@localhost:5432/\${POSTGRES_DB}"
export REDIS_URL="redis://localhost:6379/0"
export ENV=production

# Run migrations then start
alembic upgrade head
exec uvicorn app.main:app --host 0.0.0.0 --port \${BACKEND_PORT:-8000} --workers \${WORKERS:-2}
BEOF
    chmod +x "$APP_DIR/api/start.sh"

    # ── Supervisord configs for backend ───────────────────────────────
    if [ "$HAS_SYSTEMD" = "1" ]; then
        cat <<SEOF | sudo tee /etc/systemd/system/oig-backend.service >/dev/null
[Unit]
Description=OIG Backend
After=network.target postgresql.service redis-server.service
Requires=postgresql.service redis-server.service

[Service]
Type=simple
User=$USER
WorkingDirectory=$APP_DIR/api
ExecStart=$APP_DIR/api/start.sh
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SEOF
        sudo systemctl daemon-reload
        sudo systemctl enable oig-backend
        sudo systemctl start oig-backend
    else
        mkdir -p /etc/supervisor/conf.d
        cat > /etc/supervisor/conf.d/oig-backend.conf <<SEOF
[program:oig-backend]
command=$APP_DIR/api/start.sh
directory=$APP_DIR/api
user=$USER
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/var/log/oig-backend.log
stderr_logfile=/var/log/oig-backend.log
SEOF
    fi

    echo "Backend configured."

    # ── Cloudflare Tunnel (production without Docker) ─────────────────
    if [ "$INSTALL_MODE" = "production" ]; then
        echo ""
        echo "=== Setting up Cloudflare Tunnel ==="
        echo ""
        echo "Cloudflare Tunnel creates a secure outbound connection from this server"
        echo "to Cloudflare, so your domain works without opening inbound ports."
        echo ""

        # Install cloudflared
        if ! command -v cloudflared &>/dev/null; then
            echo "Installing cloudflared..."
            curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared
            chmod +x /usr/local/bin/cloudflared
        else
            echo "cloudflared already installed."
        fi

        # Check if tunnel credentials already exist (re-run scenario)
        TUNNEL_NAME="oig-$(hostname | cut -c1-8)"
        TUNNEL_CRED_DIR="/root/.cloudflared"

        if [ -d "$TUNNEL_CRED_DIR" ] && ls "$TUNNEL_CRED_DIR"/*.json &>/dev/null 2>&1; then
            echo "Existing tunnel credentials found — reusing."
        else
            echo ""
            echo "You need to authenticate cloudflared with your Cloudflare account."
            echo "This will open a URL — copy and paste it into your browser to authorize."
            echo ""
            read -p "Press Enter to start authentication..." _
            cloudflared tunnel login

            echo ""
            echo "Creating tunnel '$TUNNEL_NAME'..."
            cloudflared tunnel create "$TUNNEL_NAME"
        fi

        # Set up DNS route
        DOMAIN=$(grep "^APP_URL=" "$APP_DIR/.env" | sed 's|APP_URL=https://||')
        echo "Routing $DOMAIN → tunnel '$TUNNEL_NAME'..."
        echo "  (will overwrite existing DNS record if present)"
        cloudflared tunnel route dns --overwrite-dns "$TUNNEL_NAME" "$DOMAIN" 2>/dev/null || true

        # Supervisord / systemd config for cloudflared
        if [ "$HAS_SYSTEMD" = "1" ]; then
            cat <<TEOF | sudo tee /etc/systemd/system/cloudflared.service >/dev/null
[Unit]
Description=Cloudflare Tunnel
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/cloudflared tunnel run --url http://localhost:80 $TUNNEL_NAME
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
TEOF
            sudo systemctl daemon-reload
            sudo systemctl enable cloudflared
            sudo systemctl start cloudflared
        else
            mkdir -p /etc/supervisor/conf.d
            cat > /etc/supervisor/conf.d/cloudflared.conf <<TEOF
[program:cloudflared]
command=/usr/local/bin/cloudflared tunnel run --url http://localhost:80 $TUNNEL_NAME
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/cloudflared.log
stderr_logfile=/var/log/cloudflared.log
TEOF
        fi

        echo "Cloudflare Tunnel configured."
    fi

    # ── Start all supervisord services ────────────────────────────────
    if [ "$HAS_SYSTEMD" != "1" ]; then
        if ! pgrep -x supervisord &>/dev/null; then
            supervisord -c /etc/supervisor/supervisord.conf 2>/dev/null || true
        fi
        supervisorctl reread 2>/dev/null || true
        supervisorctl update 2>/dev/null || true
    fi

fi

# ── Wait for backend to be healthy ────────────────────────────────────
echo ""
echo "Waiting for backend to start..."
for _ in {1..60}; do
    if curl -sf http://localhost/api/health &>/dev/null || \
       curl -sf http://localhost:80/api/health &>/dev/null; then
        echo "Backend is up!"
        break
    fi
    sleep 2
done

echo ""
