#!/bin/bash
# ── App Setup ────────────────────────────────────────────────────────
# Configures .env, sets up swap, builds and starts the Docker stack.
#
# Expects these variables to be set by the parent install.sh:
#   INSTALL_MODE  — "local" or "production"
#   REPO_URL      — git clone URL
set -e

APP_DIR="/opt/oig"
INSTALL_MODE="${INSTALL_MODE:-local}"
REPO_URL="${REPO_URL:-https://github.com/YOUR_USERNAME/open-image-generator.git}"

echo "=== Setting Up Open Image Generator ==="
echo "Mode: $INSTALL_MODE"
echo ""

# ── Clone or update repo ─────────────────────────────────────────────
if [ -d "$APP_DIR/.git" ]; then
    echo "App directory exists. Pulling latest..."
    cd "$APP_DIR"
    git pull --ff-only 2>/dev/null || echo "  (already up to date)"
else
    echo "Cloning repository..."
    sudo mkdir -p "$APP_DIR"
    sudo chown "$USER:$USER" "$APP_DIR"
    git clone "$REPO_URL" "$APP_DIR"
fi

cd "$APP_DIR"

# ── Swap space ────────────────────────────────────────────────────────
if [ ! -f /swapfile ]; then
    echo ""
    echo "Adding 8GB swap space (ComfyUI's VAE decode can spill to system RAM)..."
    sudo fallocate -l 8G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    if ! grep -q '/swapfile' /etc/fstab; then
        echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
    fi
    echo "Swap configured."
else
    echo "Swap already exists."
fi

# ── Generate .env ─────────────────────────────────────────────────────
echo ""
echo "=== Configuration ==="

# Auto-generate secrets
JWT_SECRET=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -hex 32)

if [ "$INSTALL_MODE" = "local" ]; then
    # ── Local mode ────────────────────────────────────────────────────
    echo ""
    echo "Local mode — the app will be available at http://localhost"
    echo "No domain, SSL, or email service required."
    echo ""

    echo "--- Admin Account ---"
    read -p "Admin email: " ADMIN_EMAIL
    read -p "Admin username [admin]: " ADMIN_USERNAME
    ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
    while true; do
        read -sp "Admin password (min 8 chars): " ADMIN_PASSWORD
        echo ""
        if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
            break
        fi
        echo "  Password must be at least 8 characters."
    done

    echo ""
    read -p "Site name [Open Image Generator]: " SITE_NAME
    SITE_NAME="${SITE_NAME:-Open Image Generator}"

    cat > "$APP_DIR/.env" <<EOF
# ── Generated by installer (local mode) ──────────────────────────────
# $(date)

# Database
POSTGRES_USER=oig
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=open_image_gen

# Backend
BACKEND_PORT=8000
WORKERS=2
JWT_SECRET=$JWT_SECRET
JWT_EXPIRE_MINUTES=480

# URLs
CORS_ORIGIN=http://localhost
APP_URL=http://localhost

# GPU Services
COMFYUI_URL=http://host.docker.internal:8188
LMSTUDIO_URL=http://host.docker.internal:11434
LLM_MODEL=qwen3:8b

# Admin
SUPERADMIN_EMAIL=$ADMIN_EMAIL
SUPERADMIN_PASSWORD=$ADMIN_PASSWORD
EOF

    COMPOSE_FILE="docker-compose.local.yml"

else
    # ── Production mode ───────────────────────────────────────────────
    echo ""
    echo "Production mode — requires a domain and Cloudflare DNS."
    echo ""

    read -p "Domain (e.g. mysite.com): " DOMAIN
    while [ -z "$DOMAIN" ]; do
        read -p "  Domain is required: " DOMAIN
    done

    read -p "Cloudflare API token: " CF_TOKEN
    while [ -z "$CF_TOKEN" ]; do
        read -p "  Cloudflare token is required for SSL: " CF_TOKEN
    done

    echo ""
    echo "--- Admin Account ---"
    read -p "Admin email: " ADMIN_EMAIL
    read -p "Admin username [admin]: " ADMIN_USERNAME
    ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
    while true; do
        read -sp "Admin password (min 8 chars): " ADMIN_PASSWORD
        echo ""
        if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
            break
        fi
        echo "  Password must be at least 8 characters."
    done

    echo ""
    echo "--- Email (optional — skip to configure later in admin UI) ---"
    read -p "Brevo API key [skip]: " BREVO_KEY
    read -p "From email address [skip]: " FROM_EMAIL
    read -p "From name [Open Image Generator]: " FROM_NAME
    FROM_NAME="${FROM_NAME:-Open Image Generator}"

    read -p "Site name [Open Image Generator]: " SITE_NAME
    SITE_NAME="${SITE_NAME:-Open Image Generator}"

    # Write Caddyfile with the domain
    if [ ! -f "$APP_DIR/Caddyfile" ]; then
        echo "ERROR: Caddyfile not found in $APP_DIR"
        exit 1
    fi
    sed "s/yourdomain.com/$DOMAIN/g" "$APP_DIR/Caddyfile" > "$APP_DIR/Caddyfile.tmp"
    mv "$APP_DIR/Caddyfile.tmp" "$APP_DIR/Caddyfile"

    cat > "$APP_DIR/.env" <<EOF
# ── Generated by installer (production mode) ─────────────────────────
# $(date)

# Database
POSTGRES_USER=oig
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=open_image_gen

# Backend
BACKEND_PORT=8000
WORKERS=2
JWT_SECRET=$JWT_SECRET
JWT_EXPIRE_MINUTES=480

# URLs
CORS_ORIGIN=https://$DOMAIN
APP_URL=https://$DOMAIN

# GPU Services
COMFYUI_URL=http://host.docker.internal:8188
LMSTUDIO_URL=http://host.docker.internal:11434
LLM_MODEL=qwen3:8b

# Cloudflare
CLOUDFLARE_API_TOKEN=$CF_TOKEN

# Admin
SUPERADMIN_EMAIL=$ADMIN_EMAIL
SUPERADMIN_PASSWORD=$ADMIN_PASSWORD

# Email (Brevo)
BREVO_API_KEY=${BREVO_KEY:-}
EMAIL_FROM_NAME=$FROM_NAME
EMAIL_FROM_EMAIL=${FROM_EMAIL:-}
EOF

    COMPOSE_FILE="docker-compose.prod.yml"
fi

# ── Build and start ───────────────────────────────────────────────────
echo ""
echo "=== Building and starting services ==="
echo "This will build the frontend and backend Docker images (may take a few minutes)..."
echo ""

# Use sudo if user isn't in docker group yet
if groups "$USER" | grep -q docker; then
    docker compose -f "$COMPOSE_FILE" up -d --build
else
    sudo docker compose -f "$COMPOSE_FILE" up -d --build
fi

# Wait for backend to be healthy
echo ""
echo "Waiting for backend to start..."
for _ in {1..60}; do
    if curl -sf http://localhost/api/health &>/dev/null || \
       curl -sf http://localhost:80/api/health &>/dev/null; then
        echo "Backend is up!"
        break
    fi
    sleep 2
done

echo ""
