#!/bin/bash
# ── App Setup ────────────────────────────────────────────────────────
# Downloads the OIG release tarball, configures .env, sets up swap,
# builds and starts the Docker stack.
#
# Expects these variables from the parent install.sh:
#   INSTALL_MODE      — "local" or "production"
#   OIG_TARBALL_URL   — URL to the release tarball on GitHub Releases
#   OIG_VERSION       — version string (e.g. "0.1.0")
set -e

APP_DIR="/opt/oig"
INSTALL_MODE="${INSTALL_MODE:-local}"

echo "=== Setting Up Open Image Generator v${OIG_VERSION} ==="
echo "Mode: $INSTALL_MODE"
echo ""

# ── Download or update app ───────────────────────────────────────────
if [ -d "$APP_DIR" ] && [ -f "$APP_DIR/.oig-version" ]; then
    INSTALLED_VERSION=$(cat "$APP_DIR/.oig-version" | tr -d '[:space:]')
    if [ "$INSTALLED_VERSION" = "$OIG_VERSION" ]; then
        echo "v${OIG_VERSION} is already installed. Skipping download."
    else
        echo "Upgrading from v${INSTALLED_VERSION} to v${OIG_VERSION}..."
        echo "Downloading release tarball..."
        TMP_TAR=$(mktemp)
        wget --quiet --show-progress -O "$TMP_TAR" "$OIG_TARBALL_URL"
        # Preserve .env and postgres data across upgrades
        sudo rm -rf "$APP_DIR/api" "$APP_DIR/app" "$APP_DIR/Caddyfile"* "$APP_DIR/Dockerfile"* "$APP_DIR/docker-compose"*
        tar -xzf "$TMP_TAR" -C "$APP_DIR" --strip-components=1
        rm -f "$TMP_TAR"
        echo "$OIG_VERSION" > "$APP_DIR/.oig-version"
        echo "Upgrade extracted."
    fi
else
    echo "Downloading OIG v${OIG_VERSION}..."
    sudo mkdir -p "$APP_DIR"
    sudo chown "$USER:$USER" "$APP_DIR"
    TMP_TAR=$(mktemp)
    wget --quiet --show-progress -O "$TMP_TAR" "$OIG_TARBALL_URL"
    tar -xzf "$TMP_TAR" -C "$APP_DIR" --strip-components=1
    rm -f "$TMP_TAR"
    echo "$OIG_VERSION" > "$APP_DIR/.oig-version"
    echo "Download complete."
fi

cd "$APP_DIR"

# ── Swap space ────────────────────────────────────────────────────────
if [ ! -f /swapfile ]; then
    echo ""
    echo "Adding 8GB swap space (ComfyUI's VAE decode can spill to system RAM)..."
    sudo fallocate -l 8G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    if ! grep -q '/swapfile' /etc/fstab; then
        echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
    fi
    echo "Swap configured."
else
    echo "Swap already exists."
fi

# ── Generate .env ─────────────────────────────────────────────────────
# Only generate .env on first install — upgrades keep existing config
if [ -f "$APP_DIR/.env" ]; then
    echo ""
    echo "Existing .env found — keeping current configuration."
    echo "(Edit $APP_DIR/.env manually if you need to change settings)"
else
    echo ""
    echo "=== Configuration ==="

    # Auto-generate secrets
    JWT_SECRET=$(openssl rand -hex 32)
    POSTGRES_PASSWORD=$(openssl rand -hex 32)

    if [ "$INSTALL_MODE" = "local" ]; then
        # ── Local mode ────────────────────────────────────────────────
        echo ""
        echo "Local mode — the app will be available at http://localhost"
        echo "No domain, SSL, or email service required."
        echo ""

        echo "--- Admin Account ---"
        read -p "Admin email: " ADMIN_EMAIL
        read -p "Admin username [admin]: " ADMIN_USERNAME
        ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
        while true; do
            read -sp "Admin password (min 8 chars): " ADMIN_PASSWORD
            echo ""
            if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
                break
            fi
            echo "  Password must be at least 8 characters."
        done

        echo ""
        read -p "Site name [Open Image Generator]: " SITE_NAME
        SITE_NAME="${SITE_NAME:-Open Image Generator}"

        cat > "$APP_DIR/.env" <<EOF
# ── Generated by installer (local mode) ──────────────────────────────
# $(date)
# OIG v${OIG_VERSION}

# Database
POSTGRES_USER=oig
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=open_image_gen

# Backend
BACKEND_PORT=8000
WORKERS=2
JWT_SECRET=$JWT_SECRET
JWT_EXPIRE_MINUTES=480

# URLs
CORS_ORIGIN=http://localhost
APP_URL=http://localhost

# GPU Services
COMFYUI_URL=http://host.docker.internal:8188
LMSTUDIO_URL=http://host.docker.internal:11434
LLM_MODEL=qwen3:8b-nothink

# Admin
SUPERADMIN_EMAIL=$ADMIN_EMAIL
SUPERADMIN_PASSWORD=$ADMIN_PASSWORD
EOF

        COMPOSE_FILE="docker-compose.local.yml"

    else
        # ── Production mode ───────────────────────────────────────────
        echo ""
        echo "Production mode — requires a domain and Cloudflare DNS."
        echo ""

        read -p "Domain (e.g. mysite.com): " DOMAIN
        while [ -z "$DOMAIN" ]; do
            read -p "  Domain is required: " DOMAIN
        done

        read -p "Cloudflare API token: " CF_TOKEN
        while [ -z "$CF_TOKEN" ]; do
            read -p "  Cloudflare token is required for SSL: " CF_TOKEN
        done

        echo ""
        echo "--- Admin Account ---"
        read -p "Admin email: " ADMIN_EMAIL
        read -p "Admin username [admin]: " ADMIN_USERNAME
        ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
        while true; do
            read -sp "Admin password (min 8 chars): " ADMIN_PASSWORD
            echo ""
            if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
                break
            fi
            echo "  Password must be at least 8 characters."
        done

        echo ""
        echo "--- Email (optional — skip to configure later in admin UI) ---"
        read -p "Brevo API key [skip]: " BREVO_KEY
        read -p "From email address [skip]: " FROM_EMAIL
        read -p "From name [Open Image Generator]: " FROM_NAME
        FROM_NAME="${FROM_NAME:-Open Image Generator}"

        read -p "Site name [Open Image Generator]: " SITE_NAME
        SITE_NAME="${SITE_NAME:-Open Image Generator}"

        # Write Caddyfile with the domain
        if [ ! -f "$APP_DIR/Caddyfile" ]; then
            echo "ERROR: Caddyfile not found in $APP_DIR"
            exit 1
        fi
        sed "s/yourdomain.com/$DOMAIN/g" "$APP_DIR/Caddyfile" > "$APP_DIR/Caddyfile.tmp"
        mv "$APP_DIR/Caddyfile.tmp" "$APP_DIR/Caddyfile"

        cat > "$APP_DIR/.env" <<EOF
# ── Generated by installer (production mode) ─────────────────────────
# $(date)
# OIG v${OIG_VERSION}

# Database
POSTGRES_USER=oig
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=open_image_gen

# Backend
BACKEND_PORT=8000
WORKERS=2
JWT_SECRET=$JWT_SECRET
JWT_EXPIRE_MINUTES=480

# URLs
CORS_ORIGIN=https://$DOMAIN
APP_URL=https://$DOMAIN

# GPU Services
COMFYUI_URL=http://host.docker.internal:8188
LMSTUDIO_URL=http://host.docker.internal:11434
LLM_MODEL=qwen3:8b-nothink

# Cloudflare
CLOUDFLARE_API_TOKEN=$CF_TOKEN

# Admin
SUPERADMIN_EMAIL=$ADMIN_EMAIL
SUPERADMIN_PASSWORD=$ADMIN_PASSWORD

# Email (Brevo)
BREVO_API_KEY=${BREVO_KEY:-}
EMAIL_FROM_NAME=$FROM_NAME
EMAIL_FROM_EMAIL=${FROM_EMAIL:-}
EOF

        COMPOSE_FILE="docker-compose.prod.yml"
    fi
fi

# ── Determine compose file if not set (upgrade path) ─────────────────
if [ -z "$COMPOSE_FILE" ]; then
    if grep -q "CORS_ORIGIN=http://localhost" "$APP_DIR/.env" 2>/dev/null; then
        COMPOSE_FILE="docker-compose.local.yml"
    else
        COMPOSE_FILE="docker-compose.prod.yml"
    fi
fi

# ── Build and start ───────────────────────────────────────────────────
echo ""
echo "=== Building and starting services ==="
echo "This will build the frontend and backend Docker images (may take a few minutes)..."
echo ""

# Use sudo if user isn't in docker group yet (root never needs sudo)
if [ "$(id -u)" = "0" ] || groups "$USER" | grep -q docker; then
    docker compose -f "$COMPOSE_FILE" up -d --build
else
    sudo docker compose -f "$COMPOSE_FILE" up -d --build
fi

# Wait for backend to be healthy
echo ""
echo "Waiting for backend to start..."
for _ in {1..60}; do
    if curl -sf http://localhost/api/health &>/dev/null || \
       curl -sf http://localhost:80/api/health &>/dev/null; then
        echo "Backend is up!"
        break
    fi
    sleep 2
done

echo ""
